/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package it.unina.ceccarino.gaforjss.gui.mr.foreigntree;

import java.awt.Container;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JScrollPane;

/**
 *
 * @author sommovir
 */
public class TestFrame extends javax.swing.JFrame {

    /**
     * Creates new form TestFrame
     */
    public TestFrame() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        setLayout(new GridLayout(0, 1));

        MyAbstractTreeTableModel treeTableModel = new MyDataModel(createDataStructure());

        MyTreeTable myTreeTable = new MyTreeTable(treeTableModel);

        Container cPane = getContentPane();

        cPane.add(new JScrollPane(myTreeTable));

        setSize(1000, 800);
        setLocationRelativeTo(null);

    }
    
    private static MyDataNode createDataStructure() {
        List<MyDataNode> children1 = new ArrayList<MyDataNode>();
        children1.add(new MyDataNode("N12", "C12", new Date(), Integer.valueOf(50), null));
        children1.add(new MyDataNode("N13", "C13", new Date(), Integer.valueOf(60), null));
        children1.add(new MyDataNode("N14", "C14", new Date(), Integer.valueOf(70), null));
        children1.add(new MyDataNode("N15", "C15", new Date(), Integer.valueOf(80), null));
 
        List<MyDataNode> children2 = new ArrayList<MyDataNode>();
        children2.add(new MyDataNode("N12", "C12", new Date(), Integer.valueOf(10), null));
        children2.add(new MyDataNode("N13", "C13", new Date(), Integer.valueOf(20), children1));
        children2.add(new MyDataNode("N14", "C14", new Date(), Integer.valueOf(30), null));
        children2.add(new MyDataNode("N15", "C15", new Date(), Integer.valueOf(40), null));
 
        List<MyDataNode> rootNodes = new ArrayList<MyDataNode>();
        rootNodes.add(new MyDataNode("N1", "C1", new Date(), Integer.valueOf(10), children2));
        rootNodes.add(new MyDataNode("N2", "C2", new Date(), Integer.valueOf(10), children1));
        rootNodes.add(new MyDataNode("N3", "C3", new Date(), Integer.valueOf(10), children2));
        rootNodes.add(new MyDataNode("N4", "C4", new Date(), Integer.valueOf(10), children1));
        rootNodes.add(new MyDataNode("N5", "C5", new Date(), Integer.valueOf(10), children1));
        rootNodes.add(new MyDataNode("N6", "C6", new Date(), Integer.valueOf(10), children1));
        rootNodes.add(new MyDataNode("N7", "C7", new Date(), Integer.valueOf(10), children1));
        rootNodes.add(new MyDataNode("N8", "C8", new Date(), Integer.valueOf(10), children1));
        rootNodes.add(new MyDataNode("N9", "C9", new Date(), Integer.valueOf(10), children1));
        rootNodes.add(new MyDataNode("N10", "C10", new Date(), Integer.valueOf(10), children1));
        rootNodes.add(new MyDataNode("N11", "C11", new Date(), Integer.valueOf(10), children1));
        rootNodes.add(new MyDataNode("N12", "C7", new Date(), Integer.valueOf(10), children1));
        rootNodes.add(new MyDataNode("N13", "C8", new Date(), Integer.valueOf(10), children1));
        rootNodes.add(new MyDataNode("N14", "C9", new Date(), Integer.valueOf(10), children1));
        rootNodes.add(new MyDataNode("N15", "C10", new Date(), Integer.valueOf(10), children1));
        rootNodes.add(new MyDataNode("N16", "C11", new Date(), Integer.valueOf(10), children1));
        MyDataNode root = new MyDataNode("R1", "R1", new Date(), Integer.valueOf(10), rootNodes);
 
        return root;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
