/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package it.unina.ceccarino.gaforjss.gui.panels;

import it.unina.ceccarino.gaforjss.model.Settings;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Luca
 */
public class PopulationSubgroupPanel extends javax.swing.JPanel {

    /**
     * Creates new form PopulationSubgroupPanel
     */
    public PopulationSubgroupPanel() {
        initComponents();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); 
        int populationSize = Settings.getInstance().getPopulationSize();
        
        int elected = Settings.getInstance().getElectedPercentage();
        int crossoverSubgroupSize = Settings.getInstance().getCrossoverSubgroupSize();
        int mutationSubgroupSize = Settings.getInstance().getMutationSubgroupSize();
        int width = this.getWidth();
        
        //x : width = elected : 100
        
        int width_elected = (width*elected)/100;
        int width_crossover = (width*crossoverSubgroupSize)/100;
        int width_mutation = (width*mutationSubgroupSize)/100;
        int width_else = width - (width_crossover + width_elected + width_mutation);
        
        g.setColor(Color.yellow);
        g.fillRect(0, 0, width_elected, this.getHeight());
        
        g.setColor(new Color(0,102,204)); //[0,102,204]
        g.fillRect(width_elected, 0, width_crossover, this.getHeight());
        
        g.setColor(new Color(153,0,102)); //[153,0,102]
        g.fillRect(width_elected+width_crossover, 0, width_mutation, this.getHeight());
        
        g.setColor(Color.green);
        g.fillRect(width_elected+width_crossover+width_mutation, 0, width_else, this.getHeight());
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
